
annotated = {"button mushrooms" : { "umami" : 8, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "poppy seeds" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "low sodium chicken stock" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "oreo cookies" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 8 },
			 "rice syrup" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "skim milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "caraway seeds" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "brandy" : { "umami" : 1, "bitter" : 5, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "pear" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "ground turkey" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "golden brown sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "fennel bulb" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "dry bread crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "course sea salt" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "coconut cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "dried parsley" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cheese" : { "umami" : 3, "bitter" : 3, "sour" : 2, "salty": 4, "sweet" : 2 },
			 "pepperoni" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 6, "sweet" : 1 },
			 "sriracha sauce" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "baguette" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "skinless boneless chicken thighs" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "baby arugula" : { "umami" : 2, "bitter" : 6, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "dry mustard" : { "umami" : 3, "bitter" : 2, "sour" : 2, "salty": 3, "sweet" : 2 },
			 "low fat sour cream" : { "umami" : 1, "bitter" : 1, "sour" : 6, "salty": 3, "sweet" : 1 },
			 "blue cheese" : { "umami" : 3, "bitter" : 2, "sour" : 3, "salty": 5, "sweet" : 1 },
			 "shredded mozzarella" : { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "yellow onions" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cumin powder" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "cashews" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "red curry paste" : { "umami" : 4, "bitter" : 2, "sour" : 1, "salty": 6, "sweet" : 2 },
			 "cajun seasoning" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 6, "sweet" : 3 },
			 "jalapeno peppers" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "raspberry jam" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 4 },
			 "wine" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "ground cardamom" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "whipping cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "whole cranberry sauce" : { "umami" : 1, "bitter" : 3, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "shiitake mushrooms" : { "umami" : 6, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "parmigiano reggiano" : { "umami" : 4, "bitter" : 3, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "pomegranate juice" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 3 },
			 "mascarpone cheese" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "spinach leaves" : { "umami" :1, "bitter" : 4, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "puff pastry" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "corn kernels" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "light cream cheese" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 3, "sweet" : 3 },
			 "instant yeast" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "granny smith apples" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 1, "sweet" : 4 },
			 "parsley leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "ground chicken" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "unsweetened applesauce" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 3 },
			 "tapioca flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "dill" : { "umami" : 1, "bitter" : 2, "sour" : 2, "salty": 1, "sweet" : 1},
			 "oatmeal" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "gruyere cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "cheddar" : { "umami" : 3, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "almond butter" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "semi-sweet chocolate" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "cooked brown rice" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "unsweetened shredded coconut" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "nonfat greek yogurt" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "nonfat cool whip" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "sundried tomatoes" : { "umami" : 6, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 2 },
			 "sweetened shredded coconut" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "cornmeal" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "hamburger buns" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "tart apples" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 3 },
			 "hoisin sauce" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 5, "sweet" : 3 },
			 "sharp cheddar" : { "umami" : 2, "bitter" : 5, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "sherry vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 3, "salty": 3, "sweet" : 2 },
			 "canned pumpkin puree" : { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "pumpkin" : { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "maraschino cherries" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 5 },
			 "roma tomatoes" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "turbinado sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "seasoning" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "limes" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "self-raising flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "radishes" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2},
			 "sunflower seeds" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "whiskey" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 2 },
			 "roasted peanuts" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "raw cashews" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "cinnamon sticks" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "mayo" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "juice of orange" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "greens" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "milk chocolate" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "extra firm tofu" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "rice wine vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 3, "sweet" : 1 },
			 "pancetta" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 7, "sweet" : 1 },
			 "ground turmeric" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "simple syrup" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "margarine" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "fresh mint leaves" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "iceberg lettuce" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vegetable shortening" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "dried rosemary" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 2, "sweet" : 1 },
			 "lemon extract" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "rice flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "rum" : { "umami" : 1, "bitter" : 3, "sour" : 2, "salty": 10, "sweet" : 3 },
			 "ground pork" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "frozen spinach" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "old fashioned rolled oats" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "ears corn" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "bell pepper" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "lemongrass" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "dried apricots" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "bacon strips" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "bell peppers" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "confectioners sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "grapeseed oil" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white cake mix" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "tahini" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "old-fashioned oats" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "crushed red pepper" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "food coloring" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "raw honey" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "garam masala" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "allspice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "nuts" : { "umami" : 2, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "seasoned salt" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "quick cooking oats" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "broccoli" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white pepper" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "blackberries" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "beef stock" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "lime wedges" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "cooked quinoa" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "medjool dates" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "provolone cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "nutella" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "cumin seeds" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "ricotta cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "lemons" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "prosciutto" : { "umami" : 7, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "vanilla bean" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "low fat milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "fresh flat-leaf parsley" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "coconut sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "golden raisins" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "double cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "canned tomato sauce" : { "umami" : 3, "bitter" : 1, "sour" : 2, "salty": 2, "sweet" : 2 },
			 "sub rolls" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "agave nectar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "fresh cilantro leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "canned chickpeas" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "red bell peppers" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "black peppercorns" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "barbecue sauce" : { "umami" : 4, "bitter" : 1, "sour" : 2, "salty": 5, "sweet" : 3 },
			 "tequila" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "pomengranate seeds" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "whole eggs" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "pepper sauce" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "hazelnuts" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "bourbon" : { "umami" : 1, "bitter" : 4, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "cocoa" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "half & half" : { "umami" :1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "spaghetti" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "mozzarella cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "leeks" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "enchilada sauce" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 2 },
			 "sriracha" : { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "red wine" : { "umami" : 1, "bitter" : 3, "sour" : 3, "salty": 1, "sweet" : 3 },
			 "olives" : { "umami" : 1, "bitter" :3, "sour" : 1, "salty": 6, "sweet" : 1 },
			 "panko bread crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vegetable stock" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "part-skim mozzarella cheese" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "chicken breast" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "lemon peel" : { "umami" : 1, "bitter" : 3, "sour" : 4, "salty": 1, "sweet" : 1 },
			 "panko breadcrumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "beer" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 2 },
			 "mint leaves" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "rice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "milk chocolate chips" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "swiss cheese" : { "umami" : 1, "bitter" : 5, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "stevia" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "light coconut milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "romaine lettuce" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "whipped topping" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 5 },
			 "almond flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "frozen corn" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "slivered almonds" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "white chocolate" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "orange" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 5 },
			 "plain yogurt" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "feta" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "chili sauce" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "marinara sauce" : { "umami" : 3, "bitter" : 1, "sour" : 2, "salty": 4, "sweet" : 2 },
			 "russet potatoes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vanilla ice cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "peanut butter cups" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "dates" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "yogurt" : { "umami" : 1, "bitter" : 2, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "jalapenos" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "coffee" : { "umami" : 1, "bitter" : 5, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "ranch dressing" : { "umami" : 3, "bitter" : 1, "sour" : 2, "salty": 5, "sweet" : 2 },
			 "arugula" : { "umami" : 2, "bitter" : 4, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "bread crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "semisweet chocolate" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "ice cubes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "tomato sauce" : { "umami" : 3, "bitter" : 2, "sour" : 2, "salty": 4, "sweet" : 2 },
			 "black olives" : { "umami" : 2, "bitter" : 3, "sour" : 1, "salty": 7, "sweet" : 1 },
			 "whole wheat flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "icing sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "brownie mix" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "whole wheat pastry flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "fresh chives" : { "umami" : 1, "bitter" : 2, "sour" : 3, "salty": 1, "sweet" : 2 },
			 "yellow bell pepper" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "sweet potato" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 5 },
			 "shredded cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "cayenne" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "mango" : { "umami" : 1, "bitter" :1 , "sour" : 4, "salty": 1, "sweet" : 5 },
			 "sweet onion" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "white onion" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "roasted red peppers" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "pineapple juice" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 7 },
			 "capers" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 6, "sweet" : 1 },
			 "graham cracker crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "lean ground beef" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cabbage" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "brussels sprouts" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fresh mushrooms" : { "umami" : 6, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "shredded mozzarella cheese" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 2, "sweet" : 2 },
			 "salmon" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "fresh thyme leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "plain flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "peanuts" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "half and half" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "evaporated milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "grape tomatoes" : { "umami" : 2, "bitter" : 2, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "basmati rice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "tortilla chips" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "cider vinegar" : { "umami" : 1, "bitter" : 3, "sour" : 4, "salty": 1, "sweet" : 3 },
			 "yeast" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "skinless boneless chicken breast" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "yukon gold potatoes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "basil" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "mint" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white whole wheat flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fresh parsley leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vodka" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "brown rice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "graham crackers" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "egg white" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cinnamon stick" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "red potatoes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 3, "sweet" : 1 },
			 "fresh mint" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "turkey" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 }