
annotatedDict = {"button mushrooms" : { "umami" : 8, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "poppy seeds" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "low sodium chicken stock" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "oreo cookies" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 8 },
			 "rice syrup" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "skim milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "caraway seeds" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "brandy" : { "umami" : 1, "bitter" : 5, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "pear" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "ground turkey" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "golden brown sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "fennel bulb" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "dry bread crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "coarse sea salt" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "coconut cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "dried parsley" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cheese" : { "umami" : 3, "bitter" : 3, "sour" : 2, "salty": 4, "sweet" : 2 },
			 "pepperoni" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 6, "sweet" : 1 },
			 "sriracha sauce" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "baguette" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "skinless boneless chicken thighs" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "baby arugula" : { "umami" : 2, "bitter" : 6, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "dry mustard" : { "umami" : 3, "bitter" : 2, "sour" : 2, "salty": 3, "sweet" : 2 },
			 "low fat sour cream" : { "umami" : 1, "bitter" : 1, "sour" : 6, "salty": 3, "sweet" : 1 },
			 "blue cheese" : { "umami" : 3, "bitter" : 2, "sour" : 3, "salty": 5, "sweet" : 1 },
			 "shredded mozzarella" : { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "yellow onions" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cumin powder" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "cashews" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "red curry paste" : { "umami" : 4, "bitter" : 2, "sour" : 1, "salty": 6, "sweet" : 2 },
			 "cajun seasoning" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 6, "sweet" : 3 },
			 "jalapeno peppers" : { "umami" : 2, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "raspberry jam" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 4 },
			 "wine" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "ground cardamom" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "whipping cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "whole cranberry sauce" : { "umami" : 1, "bitter" : 3, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "shiitake mushrooms" : { "umami" : 6, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "parmigiano reggiano" : { "umami" : 4, "bitter" : 3, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "pomegranate juice" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 3 },
			 "mascarpone cheese" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "spinach leaves" : { "umami" :1, "bitter" : 4, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "puff pastry" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "corn kernels" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "light cream cheese" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 3, "sweet" : 3 },
			 "instant yeast" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "granny smith apples" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 1, "sweet" : 4 },
			 "parsley leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "ground chicken" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "unsweetened applesauce" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 3 },
			 "tapioca flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "dill" : { "umami" : 1, "bitter" : 2, "sour" : 2, "salty": 1, "sweet" : 1},
			 "oatmeal" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "gruyere cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "cheddar" : { "umami" : 3, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "almond butter" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "semi-sweet chocolate" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "cooked brown rice" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "unsweetened chocolate" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "nonfat greek yogurt" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "nonfat cool whip" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "sundried tomatoes" : { "umami" : 6, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 2 },
			 "sweetened shredded coconut" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "cornmeal" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "hamburger buns" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "tart apples" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 3 },
			 "hoisin sauce" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 5, "sweet" : 3 },
			 "sharp cheddar" : { "umami" : 2, "bitter" : 5, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "sherry vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 3, "salty": 3, "sweet" : 2 },
			 "canned pumpkin puree" : { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "pumpkin" : { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "maraschino cherries" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 5 },
			 "roma tomatoes" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "turbinado sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "seasoning" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "limes" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "self-raising flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "radishes" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2},
			 "sunflower seeds" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "whiskey" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 2 },
			 "roasted peanuts" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "raw cashews" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "cinnamon sticks" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "mayo" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "juice of orange" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "greens" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "milk chocolate" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "extra firm tofu" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "rice wine vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 3, "sweet" : 1 },
			 "pancetta" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 7, "sweet" : 1 },
			 "ground turmeric" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "simple syrup" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "margarine" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "fresh mint leaves" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "iceberg lettuce" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vegetable shortening" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "dried rosemary" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 2, "sweet" : 1 },
			 "lemon extract" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "rice flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "rum" : { "umami" : 1, "bitter" : 3, "sour" : 2, "salty": 10, "sweet" : 3 },
			 "ground pork" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "frozen spinach" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "old fashioned rolled oats" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "ears corn" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "bell pepper" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "lemongrass" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "dried apricots" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "bacon strips" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "bell peppers" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "confectioners sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "grapeseed oil" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white cake mix" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "tahini" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "old-fashioned oats" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "crushed red pepper" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "food coloring" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "raw honey" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "garam masala" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "allspice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "nuts" : { "umami" : 2, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "seasoned salt" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "quick cooking oats" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "broccoli" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white pepper" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "blackberries" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "beef stock" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "lime wedges" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "cooked quinoa" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "medjool dates" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "provolone cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "nutella" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "cumin seeds" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "ricotta cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "lemons" : { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 1 },
			 "prosciutto" : { "umami" : 7, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "vanilla bean" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "low fat milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "fresh flat-leaf parsley" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "coconut sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "golden raisins" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "double cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "canned tomato sauce" : { "umami" : 3, "bitter" : 1, "sour" : 2, "salty": 2, "sweet" : 2 },
			 "sub rolls" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "agave nectar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "fresh cilantro leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "canned chickpeas" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "red bell peppers" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "black peppercorns" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "barbecue sauce" : { "umami" : 4, "bitter" : 1, "sour" : 2, "salty": 5, "sweet" : 3 },
			 "tequila" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "pomegranate seeds" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "whole eggs" : { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "pepper sauce" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "hazelnuts" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "bourbon" : { "umami" : 1, "bitter" : 4, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "cocoa" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "half & half" : { "umami" :1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "spaghetti" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "mozzarella cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "leeks" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "enchilada sauce" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 2 },
			 "sriracha" : { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "red wine" : { "umami" : 1, "bitter" : 3, "sour" : 3, "salty": 1, "sweet" : 3 },
			 "olives" : { "umami" : 1, "bitter" :3, "sour" : 1, "salty": 6, "sweet" : 1 },
			 "panko bread crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vegetable stock" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "part-skim mozzarella cheese" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "chicken breast" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "lemon peel" : { "umami" : 1, "bitter" : 3, "sour" : 4, "salty": 1, "sweet" : 1 },
			 "panko breadcrumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "beer" : { "umami" : 1, "bitter" : 4, "sour" : 2, "salty": 1, "sweet" : 2 },
			 "mint leaves" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "rice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "milk chocolate chips" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "swiss cheese" : { "umami" : 1, "bitter" : 5, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "stevia" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "light coconut milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "romaine lettuce" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "whipped topping" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 5 },
			 "almond flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "frozen corn" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "slivered almonds" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "white chocolate" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "orange" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 5 },
			 "plain yogurt" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "feta" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 4, "sweet" : 2 },
			 "chili sauce" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "marinara sauce" : { "umami" : 3, "bitter" : 1, "sour" : 2, "salty": 4, "sweet" : 2 },
			 "russet potatoes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vanilla ice cream" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "peanut butter cups" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "dates" : { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "yogurt" : { "umami" : 1, "bitter" : 2, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "jalapenos" : { "umami" : 2, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "coffee" : { "umami" : 1, "bitter" : 5, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "ranch dressing" : { "umami" : 3, "bitter" : 1, "sour" : 2, "salty": 5, "sweet" : 2 },
			 "arugula" : { "umami" : 2, "bitter" : 4, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "bread crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "semisweet chocolate" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "ice cubes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "tomato sauce" : { "umami" : 3, "bitter" : 2, "sour" : 2, "salty": 4, "sweet" : 2 },
			 "black olives" : { "umami" : 2, "bitter" : 3, "sour" : 1, "salty": 7, "sweet" : 1 },
			 "whole wheat flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "icing sugar" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "brownie mix" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "whole wheat pastry flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "fresh chives" : { "umami" : 1, "bitter" : 2, "sour" : 3, "salty": 1, "sweet" : 2 },
			 "yellow bell pepper" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "sweet potato" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 5 },
			 "shredded cheese" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "cayenne" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "mango" : { "umami" : 1, "bitter" :1 , "sour" : 4, "salty": 1, "sweet" : 5 },
			 "sweet onion" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "white onion" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "roasted red peppers" : { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "pineapple juice" : { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 7 },
			 "capers" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 6, "sweet" : 1 },
			 "graham cracker crumbs" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "lean ground beef" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cabbage" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "brussels sprouts" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fresh mushrooms" : { "umami" : 6, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "shredded mozzarella cheese" : { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 2, "sweet" : 2 },
			 "salmon" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "fresh thyme leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "plain flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "peanuts" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "half and half" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "evaporated milk" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "grape tomatoes" : { "umami" : 2, "bitter" : 2, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "basmati rice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "tortilla chips" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "cider vinegar" : { "umami" : 1, "bitter" : 3, "sour" : 4, "salty": 1, "sweet" : 3 },
			 "yeast" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "skinless boneless chicken breast" : { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "yukon gold potatoes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "basil" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "mint" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white whole wheat flour" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fresh parsley leaves" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vodka" : { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "brown rice" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "graham crackers" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "egg white" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cinnamon stick" : { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "red potatoes" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "white vinegar" : { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 3, "sweet" : 1 },
			 "fresh mint" : { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "turkey" : { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },

			 "salt": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "olive oil": { "umami" : 5, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "butter": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "flour": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "sugar": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "garlic": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 2 },
			 "eggs": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "vanilla extract": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "water": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "unsalted butter": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "kosher salt": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "onion": { "umami" : 2, "bitter" : 3, "sour" : 2, "salty": 3, "sweet" : 4 },
			 "milk": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1},
			 "baking powder": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "egg": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "granulated sugar": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10},
			 "baking soda": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "salt and pepper": { "umami" : 2, "bitter" : 3, "sour" : 1, "salty": 10, "sweet" : 1},
			 "lemon juice": { "umami" : 7, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 4 },
			 "brown sugar": { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "pepper": { "umami" : 2, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "black pepper": { "umami" : 2, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cinnamon": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "garlic cloves": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 5, "sweet" : 2 },
			 "cream cheese": { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 3, "sweet" : 3 },
			 "honey": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 9 },
			 "heavy cream": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "vanilla": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "ground cinnamon": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "powdered sugar": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "vegetable oil": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "parmesan cheese": { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "garlic powder": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "oregano": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "lemon zest": { "umami" : 1, "bitter" : 3, "sour" : 10, "salty": 1, "sweet" : 2},
			 "canola oil": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "sea salt": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "sour cream": { "umami" : 1, "bitter" : 1, "sour" : 6, "salty": 1, "sweet" : 2 },
			 "carrots": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "bacon": { "umami" : 9, "bitter" : 1, "sour" : 1, "salty": 7, "sweet" : 1 },
			 "lime juice": { "umami" : 1, "bitter" : 2, "sour" : 10, "salty": 10, "sweet" : 4 },
			 "cilantro": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "light brown sugar": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "cornstarch": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "ground cumin": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "red onion": { "umami" : 2, "bitter" : 3, "sour" : 2, "salty": 3, "sweet" : 4 },
			 "extra virgin olive oil": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "ground pepper": { "umami" : 2, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fresh parsley": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "celery": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "chili powder": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "avocado": { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "maple syrup": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 9 },
			 "green onions": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "cayenne pepper": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "buttermilk": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "dijon mustard": { "umami" : 1, "bitter" : 4, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "nutmeg": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "whole milk": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "egg whites": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "paprika": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "juice of lemon": { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 4 },
			 "pecans": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "yellow onion": { "umami" : 2, "bitter" : 3, "sour" : 2, "salty": 3, "sweet" : 4 },
			 "oil": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "walnuts": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "canned tomatoes": { "umami" : 5, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 5 },
			 "all purpose flour": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "soy sauce": { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 8, "sweet" : 1 },
			 "red pepper flakes": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "coconut oil": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "worcestershire sauce": { "umami" : 2, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "blueberries": { "umami" : 3, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 6 },
			 "mayonnaise": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "egg yolks": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "skinless boneless chicken breasts": { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "almonds": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 2 },
			 "fresh ginger": { "umami" : 1, "bitter" : 3, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "red bell pepper": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "chocolate chips": { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "balsamic vinegar": { "umami" : 2, "bitter" : 1, "sour" : 9, "salty": 2, "sweet" : 1 },
			 "chicken broth": { "umami" : 5, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "ginger": { "umami" : 1, "bitter" : 3, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "fresh cilantro": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "almond milk": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "scallions": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "cocoa powder": { "umami" : 1, "bitter" : 4, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "strawberries": { "umami" : 3, "bitter" : 1, "sour" : 6, "salty": 1, "sweet" : 6 },
			 "ground ginger": { "umami" : 1, "bitter" : 3, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "zucchini": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "carrot": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "peanut butter": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "garlic clove": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "onion powder": { "umami" : 2, "bitter" : 3, "sour" : 2, "salty": 3, "sweet" : 4 },
			 "unsweetened cocoa powder": { "umami" : 1, "bitter" : 5, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "tomato paste": { "umami" : 5, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 5 },
			 "spinach": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "juice of lime": { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 4 },
			 "fresh basil": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "tomatoes": { "umami" : 5, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 5 },
			 "ground nutmeg": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "cherry tomatoes": { "umami" : 5, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 5 },
			 "parsley": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "banana": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 5 },
			 "apple cider vinegar": { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 3 },
			 "bananas": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 5 },
			 "mushrooms": { "umami" : 6, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "hot sauce": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "cumin": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "tomato": { "umami" : 5, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 5},
			 "potatoes": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "parmesan": { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "confectioners' sugar": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "jalapeno": { "umami" : 2, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "orange zest": { "umami" : 1, "bitter" : 3, "sour" : 6, "salty": 1, "sweet" : 4 },
			 "white sugar": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "sesame oil": { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "onions": { "umami" : 2, "bitter" : 3, "sour" : 2, "salty": 3, "sweet" : 4 },
			 "bread": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "vegetable broth": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "chicken stock": { "umami" : 5, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "semisweet chocolate chips": { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 2, "sweet" : 6 },
			 "sea-salt": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "shredded cheddar cheese": { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "feta cheese": { "umami" : 3, "bitter" : 1, "sour" : 2, "salty": 4, "sweet" : 1 },
			 "dried thyme": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fresh thyme": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "Salt & Pepper": { "umami" : 2, "bitter" : 3, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "sharp cheddar cheese": { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "smoked paprika": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "shrimp": { "umami" : 5, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "sweetened condensed milk": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "thyme": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "shallots": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "coconut": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "ground cloves": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 5, "sweet" : 1 },
			 "bay leaf": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "dry white wine": { "umami" : 1, "bitter" : 3, "sour" : 3, "salty": 1, "sweet" : 2 },
			 "fresh rosemary": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "apples": { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "sesame seeds": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "molasses": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "heavy whipping cream": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "bay leaves": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "ground beef": { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "goat cheese": { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 3, "sweet" : 2 },
			 "red wine vinegar": { "umami" : 1, "bitter" : 2, "sour" : 7, "salty": 1, "sweet" : 3 },
			 "low sodium chicken broth": { "umami" : 4, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "green bell pepper": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "marshmallows": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "orange juice": { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 7 },
			 "rice vinegar": { "umami" : 2, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 1 },
			 "lemon": { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 4 },
			 "semi sweet chocolate chips": { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 2, "sweet" : 6 },
			 "shallot": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 3 },
			 "canned black beans": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "chocolate": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "curry powder": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "almond extract": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "dark brown sugar": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "plain greek yogurt": { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 6 },
			 "corn syrup": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 10 },
			 "cheddar cheese": { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "raspberries": { "umami" : 1, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 5 },
			 "monterey jack cheese": { "umami" : 3, "bitter" : 2, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "whipped cream": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 9 },
			 "bbq sauce": { "umami" : 2, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "cucumber": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fish sauce": { "umami" : 5, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 3 },
			 "lime zest": { "umami" : 1, "bitter" : 3, "sour" : 10, "salty": 1, "sweet" : 4 },
			 "dark chocolate chips": { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 2, "sweet" : 6 },
			 "egg yolk": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cake flour": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "kale": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "peas": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "low sodium soy sauce": { "umami" : 5, "bitter" : 1, "sour" : 1, "salty": 6, "sweet" : 1 },
			 "raisins": { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 5 },
			 "rosemary": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cream of tartar": { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 1 },
			 "cherries": { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 4 },
			 "butternut squash": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "ketchup": { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 5 },
			 "creamy peanut butter": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "salted butter": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "mustard": { "umami" : 3, "bitter" : 2, "sour" : 2, "salty": 3, "sweet" : 2 },
			 "sprinkles": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 7 },
			 "chicken": { "umami" : 7, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "dark chocolate": { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 2, "sweet" : 6 },
			 "lettuce": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "canned coconut milk": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "peaches": { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 6 },
			 "baby spinach": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "apple": { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 4 },
			 "cauliflower": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "greek yogurt": { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 6 },
			 "active yeast": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cream": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 8 },
			 "bittersweet chocolate": { "umami" : 1, "bitter" : 3, "sour" : 1, "salty": 1, "sweet" : 6 },
			 "sweet potatoes": { "umami" : 2, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 1 },
			 "asparagus": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "lime": { "umami" : 1, "bitter" : 1, "sour" : 10, "salty": 1, "sweet" : 3 },
			 "pumpkin puree": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "fresh dill": { "umami" : 1, "bitter" : 1, "sour" : 6, "salty": 1, "sweet" : 3 },
			 "beef broth": { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "salsa": { "umami" : 2, "bitter" : 1, "sour" : 3, "salty": 2, "sweet" : 5 },
			 "artichoke hearts": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "pineapple": { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 6 },
			 "ice": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "garlic salt": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "pine nuts": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "jalapeno pepper": { "umami" : 2, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "flour tortillas": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 1 },
			 "quinoa": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "dried cranberries": { "umami" : 1, "bitter" : 2, "sour" : 4, "salty": 1, "sweet" : 4 },
			 "applesauce": { "umami" : 1, "bitter" : 1, "sour" : 4, "salty": 1, "sweet" : 5 },
			 "coconut flour": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "green beans": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "chives": { "umami" : 3, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "ham": { "umami" : 5, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "white chocolate chips": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 2, "sweet" : 10 },
			 "pumpkin pie spice": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 4 },
			 "italian seasoning": { "umami" : 2, "bitter" : 1, "sour" : 2, "salty": 3, "sweet" : 2 },
			 "shredded chicken": { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "dried basil": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "corn tortillas": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "coconut milk": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 2 },
			 "chicken breasts": { "umami" : 6, "bitter" : 1, "sour" : 1, "salty": 4, "sweet" : 1 },
			 "basil leaves": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "pasta": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "kalamata olives": { "umami" : 5, "bitter" : 1, "sour" : 4, "salty": 3, "sweet" : 2 },
			 "ground allspice": { "umami" : 1, "bitter" : 2, "sour" : 2, "salty": 2, "sweet" : 2 },
			 "black beans": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "white wine": { "umami" : 1, "bitter" : 1, "sour" : 3, "salty": 1, "sweet" : 3 },
			 "coarse salt": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 10, "sweet" : 1 },
			 "rolled oats": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "cranberries": { "umami" : 1, "bitter" : 1, "sour" : 5, "salty": 1, "sweet" : 4 },
			 "avocados": { "umami" : 1, "bitter" : 1, "sour" : 2, "salty": 1, "sweet" : 4 },
			 "shortening": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "broccoli florets": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "ground coriander": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "pie crust": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 3, "sweet" : 2 },
			 "white wine vinegar": { "umami" : 1, "bitter" : 1, "sour" : 8, "salty": 1, "sweet" : 1 },
			 "green onion": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 3 },
			 "chia seeds": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "fresh basil leaves": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "bread flour": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "peanut oil": { "umami" : 2, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "oats": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 1, "sweet" : 1 },
			 "breadcrumbs": { "umami" : 1, "bitter" : 1, "sour" : 1, "salty": 2, "sweet" : 1 },
			 "flat-leaf parsley": { "umami" : 1, "bitter" : 2, "sour" : 1, "salty": 1, "sweet" : 1 },
			 }

def find_missing (lst, annotated):
	for i in lst:
		if i[0] not in annotated.keys():
			print (i)

def get_annotated():
	return annotatedDict
